import { Router } from "express"; // IMPORTAMOS MODULO ROUTER PARA PODER CREAR URLS / RUTAS PARA LA APP
import appControllers from "../controllers/appController.mjs"; // IMPORTACION DE LOS CONTROLOADORES ( FUNCIONES QUE MANEJAN LOS REQ / RES)

const router = Router(); // SE INVOCA EL MODULO ROUTER EN UNA VARIABLE PARA LUEGO UTILIZAR SUS METODOS

router.get("/prueba1", "ACA SE EJECUTA EL CONTROLLER CORRESPONDIENTE"); // SE CREA LA RUTA /PRUEBA1 Y EN ESA RUTA SE EJECUTA LA FUNCION TRAER SEGUIDORES DESDE APP CONTROLLER

export default router;
